### ISSUE TITLE
I am missing logs since the upgrade of the image to 2.19.1

### ISSUE THREAD

**Issue by gabuzo-scw** [aws/aws-for-fluent-bit#236] opened 2021-09-15 06:30 UTC
### Describe the question/issue

Not all logs are shipped from multi-task service in ECS.  
I have an ECS service that is configured to have desired task count/minimum task count of 4.  Each task is configured to have fluentbit/firelens as a sidecar along with my actual application and takes care of sending the logs to datadog.   I used to be able to view all the logs for all 4 containers/tasks but since 1-Sep, i started to notice some missing logs.  

Downgrading to the previous version of the image resolves my issue.

### Configuration

ECS Task Definition (some parts redacted)
{
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::account:role/ecs-role",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awsfirelens",
        "secretOptions": [
          {
            "valueFrom": "arn:aws:ssm:region:account:parameter/datadog/DD_API_KEY",
            "name": "DD_API_KEY"
          },
          {
            "valueFrom": "arn:aws:ssm:region:account:parameter/datadog/DD_API_KEY",
            "name": "apikey"
          }
        ],
        "options": {
          "dd_message_key": "log",
          "compress": "gzip",
          "provider": "ecs",
          "dd_service": "backend",
          "Host": "pvtlink.logs.datadoghq.com",
          "TLS": "on",
          "dd_source": "ecs_fargate",
          "dd_tags": "env:uat,env_type:nonprod",
          "Name": "datadog"
        }
      },
      "entryPoint": null,
      "portMappings": [
        XXXXXXXXXXX
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 2028,
      "environment": [
        XXXXXXXXXXXXXXXXXXX
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": [
        XXXXXXXXXXX
      ],
      "dockerSecurityOptions": null,
      "memory": 3584,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": 120,
      "image": "?????????????",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": false,
      "interactive": false,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": false,
      "user": null,
      "readonlyRootFilesystem": false,
      "dockerLabels": {
        "com.tag.env": "uat",
        "com.tag.source": "ecs_fargate",
        "com.datadoghq.ad.instances": "[{\"host\": \"%%host%%\", \"port\": \"3000\"}]",
        "com.datadoghq.ad.check_names": "[\"backend\"]",
        "com.datadoghq.ad.init_configs": "[{}]",
        "com.datadoghq.ad.logs": "[{}]",
        "com.tag.env_type": "nonprod",
        "com.tag.app": "backend"
      },
      "systemControls": null,
      "privileged": false,
      "name": "backend"
    },
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": null,
      "entryPoint": null,
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 10,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": 256,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": 120,
      "image": "public.ecr.aws/aws-observability/aws-for-fluent-bit:latest",
      "startTimeout": null,
      "firelensConfiguration": {
        "type": "fluentbit",
        "options": {
          "enable-ecs-log-metadata": "true"
        }
      },
      "dependsOn": null,
      "disableNetworking": false,
      "interactive": false,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": false,
      "user": "0",
      "readonlyRootFilesystem": false,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": false,
      "name": "firelens"
    }
  ],
  "placementConstraints": [],
  "memory": "4096",
  "taskRoleArn": null,
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "XXXXXXXXXXX",
  "family": "backend",
  "requiresAttributes": [
    XXXXXXXXXXX
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "2048",
  "revision": NNNN,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}

### Fluent Bit Version Info

public.ecr.aws/aws-observability/aws-for-fluent-bit:latest has the issue so I downgraded back to version 2.19.0

###  Cluster Details

Fluentbit is configured as container sidecar in ECS Fargate.
There are minimum of 3 containers configured to run at one time.

### Steps to reproduce issue

Set desired count to at least 2 and observe the logs.
You will notice that not all the logs are going through and some log messages are occasionally dropped.

**Comment by amleczko** [comment] 2021-09-15 11:27
We are having exactly the same problem with the `2.19.1` image.

**Comment by hosiukeung** [comment] 2021-09-16 08:48
We are using exactly the same setup with ECS (Fargate) + AWS Fluent Bit, `latest` tag (`2.19.1`) is causing message loss.

**Comment by bplegend** [comment] 2021-09-16 17:21
Likely related to [DNS timeout](https://github.com/aws/aws-for-fluent-bit/issues/233)

**Comment by PettitWesley** [comment] 2021-09-20 17:39
Please enable CloudWatch logging for the firelens container so that you can see the fluent bit logs and know why its failing. Without that information it's really impossible to tell what's going on. 

For example, as shown here, the firelens container needs to use a different log driver: https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/mainline/examples/fluent-bit/kinesis-firehose/task-definition.json#L13

We also recommend downgrading to the stable tag: https://github.com/aws/aws-for-fluent-bit#using-the-stable-tag

Alternatively if this is the DNS issue, then that one is pending release (though the issue is also not seen in the stable tag so you can use that too).

**Comment by cmbailey87** [comment] 2021-09-21 20:31
We had to version pin to version 2.18.0 in order to make it work..


`"image": "public.ecr.aws/aws-observability/aws-for-fluent-bit:2.18.0"`

**Comment by karthikeayan** [comment] 2021-09-23 15:16
Got the same issue. Here is the log from log_router
```
[2021/09/23 15:15:21] [ warn] [net] getaddrinfo(host='http-intake.logs.datadoghq.eu', err=12): Timeout while contacting DNS servers
```

**Comment by zhonghui12** [comment] 2021-10-01 18:05
Hi all, there is a new release out yesterday which fixes the DNS issue: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.20.0. Could you please try the latest image to see if the problem has been resolved? Thanks.

**Comment by DevBOFH** [comment] 2021-10-01 23:45
2.20.0 fixed the dns timeout issue for me.

**Comment by zhonghui12** [comment] 2021-10-20 18:22
Close this one for no more issues for now. Feel free to reopen it if the problem still exists. Thanks.

**Closed by zhonghui12** 2021-10-20 18:22 UTC
