### ISSUE TITLE
Question: What are the differences between aws-for-fluent-bit and fluent-bit repo?

### ISSUE THREAD

**Issue by Genry1** [aws/aws-for-fluent-bit#283] opened 2021-12-30 11:10 UTC
I was wondering what are the main differences between this repo and https://github.com/fluent/fluent-bit. And if we can apply these configs to the fluent-bit repo to have the same results in the fluent-bit repo.

I've tested these two repo's with the same config, but got really different performance results. 
Wasn't able to use the version 1.8.11 from Fluent-Bit as it still have the bug that it doesn't use the IDMSv1 if v2 is not available. But I have compared it with the aws-for-fluent-bit:2.20.0 and the difference was the same as with 2.21.5.
Also I've noticed that aws-for-fluent-bit discards the records if it can't deliver more, fluent-bit on the other side retries them later. The CPU that is used by 1.8.7 is already very big and differs a lot from aws-for-fluent-bit version.

The resources that were provided for fluent-bit container:
`
limits:
  cpu: 3000m
  memory: 3000Mi
requests:
  cpu: 500m
  memory: 100Mi
`

| FLB Version  | Test duration | actual duration  | messages/s | distinct  | total | expected  | Avg. CPU | Avg. Memory |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| aws-for-fluent-bit:2.21.5 (1.8.11)  | 5 min  | 5 min  | 20.000  | 5.048.620  | 5.048.620  | 6.000.000  | 139.97  | 50.6 MB  |
| aws-for-fluent-bit:2.21.5 (1.8.11)  | 5 min  | 5 min  | 18.000  | 5.242.295  | 5.242.295  | 5.400.000  | 139.27  | 52.1 MB  |
| aws-for-fluent-bit:2.21.5 (1.8.11)  | 5 min  | 5 min  | 17.000  | 5.100.000  | 5.100.000  | 5.100.000  | 137.94  | 51.3 MB  |
| aws-for-fluent-bit:2.21.5 (1.8.11)  | 5 min  | 5 min  | 15.000  | 4.500.000  | 4.514.839  | 4.500.000  | 129.93  | 52.2 MB  |
| fluent-bit:1.8.7  | 5 min  | 5 min  | 4.000  | 1.200.000  | 1.200.499  | 1.200.000  | 300.23  | 39.2 MB  |
| fluent-bit:1.8.7  | 5 min  | 5 min  | 3.000  | 900.000  | 900.000  | 900.000  | 215.03  | 23.5 MB  |
| fluent-bit:1.7.5  | 5 min  | ~20 min (retry)  | 5.000  | 1.500.000  | 1.664.499  | 1.500.000  | 43.55  | 55 MB  |
| fluent-bit:1.7.5  | 5 min  | ~6.4 min (retry)  | 4.000  | 1.200.000  | 1.266.000  | 1.200.000  | 35.87  | 21.6 MB  |
| fluent-bit:1.7.5  | 5 min  | 5 min  | 3.000  | 900.000  | 909.000  | 900.000  | 25.87  | 13.4 MB  |

Here is the config that was used:

     [SERVICE]
        Flush                           1
        Daemon                          Off
        Log_File                        /var/log/fluent-bit.log
        Log_Level                       debug
        Parsers_File                    parsers.conf
        storage.path                    /var/log/flb_buffers
        storage.metrics                 On
        HTTP_Server                     On
        HTTP_Listen                     0.0.0.0
        HTTP_Port                       2020
   
    [INPUT]
        Name                            tail
        Path                            /var/log/containers/test*.log
        Exclude_Path                    /var/log/containers/*fluent-bit*.log
        Tag                             kube.*
        Parser                          docker
        Skip_Long_Lines                 On
        Read_from_Head                  On
        Refresh_Interval                5
        DB                              /var/log/flb.db
        Mem_Buf_Limit                   2GB
 
    # Parse log record
    [FILTER]
        Name                            kubernetes
        Match                           kube.var.log.*
        Merge_Log                       On
        Keep_Log                        Off
        K8S-Logging.Parser              On
        Buffer_Size                     10MB
        Labels                          Off
        Annotations                     Off
        DNS_Wait_Time                   5
        DNS_Retries                     1
 
    [FILTER]
        Name                            nest
        Match                           kube.var.log.*
        Operation                       lift
        Nested_under                    kubernetes
 
    [FILTER]
        Name                            modify
        Match                           kube.var.log.*
        Rename                          namespace_name _role
        Rename                          host _private_ip
        Copy                            _private_ip _public_ip
        Add                             _realm ${REALM}
        Add                             _availability_zone ${REGION}
        Copy                            pod_id _host_sid
        Copy                            pod_id _instance_id
        Copy                            pod_name _private_hostname
        Copy                            pod_name _public_hostname
        Rename                          docker_id container_id
        Rename                          stream source
 
    [OUTPUT]
        Name                            kinesis_streams
        Match                           kube.var.log.*
        region                          us-east-1
        stream                          log-stream-dev
        auto_retry_requests             true
        workers                         3
        Retry_Limit                     5
`

**Comment by DrewZhang13** [comment] 2022-01-03 07:36
So the AWS for Fluent Bit image includes the following contents:

* A base linux image (currently Amazon Linux)
* Fluent Bit
* Several Fluent Bit Go Plugins

There should be no difference for fluent bit part if you are not using the go plugins provided by aws for fluent bit. 
For the issue you mentioned: `Also I've noticed that aws-for-fluent-bit discards the records if it can't deliver more, fluent-bit on the other side retries them later`
The retry is actually configurable in fluent bit and aws for fluent bit side, see the related document there: 
https://docs.fluentbit.io/manual/administration/scheduling-and-retries#configuring-retries

For the performance result you put, the big difference is messages/s which could have impact on the result. But it didn't compare for fluent bit and aws for fluent bit in the same messages/s rate. Could you try to see the difference within the same message rate?

**Comment by Genry1** [comment] 2022-01-03 09:13
Hey Drew, 

The problem with fluent-bit:1.8.7 is that is hitting the CPU limit (300) at 4.000/s and the pod is being restarted, even if I go higher like CPU (1000). I tried aws-for-fluent-bit:2.20.0 and the CPU consumption is not that high compared to official fluent-bit image. 

The Retry_Limit is actually set in my output config, but the messages are not getting retried after 5 minutes. On the other hand with fluent-bit images it is visible that there is an exponential backoff retry, that's why some tests are getting completed in 20 mins or more (because of retry), when sending a higher amount of messages.

**Comment by f0o** [comment] 2022-01-04 07:39
@Genry1 I recommend retrying the test with upstream 1.8.11 as they just merged a PR that forcefully stops retries to obey graceful shutdown periods which did not exist in prior releases leading to fluentbit not shutting down in a timely manner. it could be that this upstream change is what discards the messages in your tests.

**Comment by Genry1** [comment] 2022-01-04 10:07
@f0o 
The test which performed the best was aws-for-fluent-bit:2.21.5 which is 1.8.11 version. But if I am sending e.g. 20.000 records/s then the retries are not visible and lots of records are discarded. Also by the CPU and Output Bytes activity it is visible that after 5 mins (time when records are produced) nothing is happening.

An interesting thing that the official 1.8.11 doesn't have the fix for fallback to IDMSv1 if v2 is not available, but aws version works fine. Therefore I was not able to perform any tests with official 1.8.11 version.

**Comment by matthewfala** [comment] 2022-01-04 20:07
Hi @Gentry1,
We actually do add a set of cherry picked fluent bit patches to the aws-for-fluent-bit fluent bit build on top of the specified version of fluent bit. You can see a list of these cherry picks here: https://github.com/aws/aws-for-fluent-bit/blob/mainline/AWS_FLB_CHERRY_PICKS and also in the version notes.

As you mentioned, an IMDS patch as well as a patch for OpenSSL, and performant utility functions are included in aws-for-fluent-bit. We're working on getting these patches merged upstream, but until then, we'll keep including them in aws-for-fluent-bit.

As per log loss, are you able to see the debug logs? My guess is that you are seeing the Connection Timeout error and Broken Pipe error, which is known to cause log loss at high throughput. We have a fix, but it may be a few weeks before it, or something similar gets merged in.

**Comment by Genry1** [comment] 2022-01-05 16:10
Hey @matthewfala,
Thanks a lot for the details provided. This makes sense now. Will be waiting for the fix of Connection Timeout and Broken Pipe errors.

**Comment by matthewfala** [comment] 2022-01-06 02:26
You're welcome!
While it may be some time before we get a solution up on upstream Fluent Bit, we have the broken pipe and connection timeout patch added to this custom aws-for-fluent-bit which is being tested:
826489191740.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-for-fluent-bit:1.8.11-1.8-event-loop-priority
which is built from: https://github.com/fala-aws/aws-for-fluent-bit/tree/1.8-event-loop-priority

Would you help test the image out and let me know if it resolves your Connection Timeout and Broken Pipe problems?

If you try it out, please let me know if you see any instability in the patched image, and if so, if you could provide debug logs by setting the debug log_level option on Fluent Bit, that would really help!

**Comment by Genry1** [comment] 2022-01-07 13:49
I am not able to build the image from this branch unfortunately. This is the error I am getting: 
`[+] Building 2.4s (7/53)                                                        
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for public.ecr.aws/amazonlinux/amazonlinux:l  0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 667B                                          0.0s
 => ERROR FROM docker.io/library/aws-fluent-bit-plugins:latest             1.7s
 => => resolve docker.io/library/aws-fluent-bit-plugins:latest             1.7s
 => CANCELED [builder  1/30] FROM public.ecr.aws/amazonlinux/amazonlinux:  1.7s
 => => resolve public.ecr.aws/amazonlinux/amazonlinux:latest@sha256:69a7e  0.0s
 => => sha256:69a7e4782be3dc25f610582d6ad7a88d1db7db08f272481 770B / 770B  0.0s
 => => sha256:88fd3b6871dcc60b44923c03c7481454e936bce4837ea18 529B / 529B  0.0s
 => => sha256:d7b15f736b7ebb3ef61d24ca174193eb9f178a499fa 1.48kB / 1.48kB  0.0s
 => => sha256:8b8a142162d22658bdf0283afcd00a9dd216c66379 3.15MB / 62.09MB  1.7s
 => [auth] library/aws-fluent-bit-plugins:pull token for registry-1.docke  0.0s
------
 > FROM docker.io/library/aws-fluent-bit-plugins:latest:
------
failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

**Comment by matthewfala** [comment] 2022-01-07 18:23
Hi @Gentry1, you shouldn't need to build the image, I made this custom image public if you want to try it:
826489191740.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-for-fluent-bit:1.8.11-1.8-event-loop-priority

Just use this instead of the official FireLens image.

If you don't have access to the custom image, then please let me know, but it should be public. Some others have tested the image as well and do have access.

**Comment by matthewfala** [comment] 2022-01-26 00:56
Does that mean that the broken pipe and connection issues are resolved?

**Comment by Genry1** [comment] 2022-01-31 12:35
Hey @matthewfala, sorry for the long reply.
I've tried with bigger file sizes which are not rotating so often. The result is quite similar even with the version that you've provided.
I've tried to send 20.000 per second during 300 seconds, so in total there should be 6.000.000 log records. But the maximum I got is 4.572.401 distinct and total 4.814.620 (because of retries).
The CPU doesn't go higher than 145, even if I increase the amount of workers, it doesn't change.

The only errors that I see are:
`
[2022/01/31 12:18:14] [error] [output:kinesis_streams:kinesis_streams.0] 36 out of 500 records failed to be delivered, will retry this batch, log-stream-dev
[2022/01/31 12:18:14] [error] [output:kinesis_streams:kinesis_streams.0] Failed to send log records
[2022/01/31 12:18:14] [error] [output:kinesis_streams:kinesis_streams.0] Failed to send records to kinesis
`

**Comment by matthewfala** [comment] 2022-01-31 21:45
@Genry1,
Thanks a lot for your in depth test of the issue.
Will try to reproduce this with the following information:
```
logs -> kinesis streams at 20,000 logs per second for 5 minutes.
```
But we do need one more detail.
What do your logs look like, how large are they?

A teammate tested 25,000 logs per second, 1kb each. She says no loss, and little duplication.

**Comment by Genry1** [comment] 2022-02-01 09:47
@matthewfala 
Thanks to you for looking into it.
The log is approximately 1kb as well. Here is an example of how it looks:
`
{"time"=>"2022-01-26T12:48:42.586707862Z", "thread"=>"main", "_instance_id"=>"f2af14a5-a87b-4b0c-a206-894ae229e497", "_host_sid"=>"f2af14a5-a87b-4b0c-a206-894ae229e497", "_private_ip"=>"ip-10-200-100-200.ec2.internal", "_public_ip"=>"ip-10-200-100-200.ec2.internal", "container_id"=>"4ab2cc93a8710fc2dfcb897a53462cc1622ce9f45519e9d6b3e355131912119f", "timestamp"=>"2022-01-26T12:48:42.164320+02:00", "container_hash"=>"busybox@sha256:5acba83a746c7608ed544dc1533b87c737a0b0fb730301639a0179f9344b1678", "container_image"=>"busybox:latest", "_role"=>"observability", "_realm"=>"dev-us1", "container_name"=>"dwtester", "source"=>"stdout", "logger"=>"001", "level"=>"INFO", "tag"=>"app.dropwizard-tester.dwtester.stdout", "message"=>"Hello World! 1", "_availability_zone"=>"us-east-1", "pod_name"=>"qtcodwtester", "pod_id"=>"f2af14a5-a87b-4b0c-a206-894ae229e497", "_public_hostname"=>"wtester", "_private_hostname"=>"dwtester"}
`

**Comment by Genry1** [comment] 2022-02-01 09:59
And here is the config that we are using:

    [SERVICE]
        Flush                           1
        Daemon                          Off
        Log_File                        /var/log/fluent-bit.log
        Log_Level                       debug
        Parsers_File                    parsers.conf
        storage.path                    /var/log/flb_buffers
        storage.metrics                 On
        HTTP_Server                     On
        HTTP_Listen                     0.0.0.0
        HTTP_Port                       2020

    [INPUT]
        Name                            tail
        Path                            /var/log/containers/qtco*.log
        Exclude_Path                    /var/log/containers/*fluent-bit*.log
        Tag                             kube.*
        Parser                          docker
        Skip_Long_Lines                 On
        Read_from_Head                  On
        Refresh_Interval                5
        DB                              /var/log/flb.db
        Mem_Buf_Limit                   2GB

    # Parse log record
    [FILTER]
        Name                            kubernetes
        Match                           kube.var.log.*
        Merge_Log                       On
        Keep_Log                        Off
        K8S-Logging.Parser              On
        Buffer_Size                     10MB
        Labels                          Off
        Annotations                     On
        DNS_Wait_Time                   5
        DNS_Retries                     1
        Kube_URL                        https://kubernetes.default.svc.cluster.local:443
        Use_Kubelet                     true
        Kubelet_Port                    10250

    [FILTER]
        Name                            grep
        Match                           kube.var.log.*
        Regex                           $kubernetes['annotations']['logger'] fluentbit

    [FILTER]
        Name                            nest
        Match                           kube.var.log.*
        Operation                       lift
        Nested_under                    kubernetes

    [FILTER]
        Name                            modify
        Match                           kube.var.log.*
        Rename                          namespace_name _role
        Rename                          host _private_ip
        Copy                            _private_ip _public_ip
        Add                             _realm ${REALM}
        Add                             _availability_zone ${REGION}
        Copy                            pod_id _host_sid
        Copy                            pod_id _instance_id
        Copy                            pod_name _private_hostname
        Copy                            pod_name _public_hostname
        Rename                          docker_id container_id
        Rename                          stream source
        Remove                          annotations

    [FILTER]
        Name                            lua
        Match                           kube.var.log.*
        script                          /fluent-bit/etc/lua/add-destination-tag.lua
        call                            add_destination_tag

    [OUTPUT]
        Name                            kinesis_streams
        Match                           kube.var.log.*
        region                          us-east-1
        role_arn                        <some_arn>
        stream                          log-stream-dev
        auto_retry_requests             true
        workers                         3
        Retry_Limit                     5

Parsers:

    [PARSER]
        Name                            docker
        Format                          json
        Time_Key                        time
        Time_Format                     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep                       On

Lua function:

    function add_destination_tag(tag, timestamp, record)
        new_record = record
        new_record["tag"] = "app." .. record["_role"] .. "." .. record["container_name"] .. "." .. record["source"]
        return 2, 0, new_record
    end

**Comment by Genry1** [comment] 2022-02-01 10:36
I noticed as well that If I add more outputs with the same destination to check if Fluent-Bit is able to deliver more trough-put, and it actually is, but of course because of that, the message would be duplicated. So I've tried to add a random number between 1 and 3 to each record and rewrite the tag with that number, which will be included in the output as well to load balance and increase the trough-put. 
Some logs are going trough, but there are lots of errors like below, which reduced the trough-put when having a single output: 
`
[2022/02/01 10:30:33] [error] [input:emitter:emitter_for_rewrite_tag.5] error registering chunk with tag: kinesis.3
`
`
[2022/02/01 10:30:33] [error] [input:emitter:emitter_for_rewrite_tag.5] error registering chunk with tag: kinesis.2
`
`
[2022/02/01 10:30:33] [error] [input:emitter:emitter_for_rewrite_tag.5] error registering chunk with tag: kinesis.1
`

And here is the config that I've used, it's basically the same, only the last part is modified:

      [FILTER]
          Name                            rewrite_tag
          Match                           kube.var.log.*
          Rule                            $random ^(.*)$ kinesis.$0 false
      
      [OUTPUT]
          Name                            kinesis_streams
          Match                           kinesis.1
          region                          us-east-1
          stream                          log-stream-dev
          role_arn                        <some_arn>
          auto_retry_requests             true
          workers                         3
          Retry_Limit                     5
      
      [OUTPUT]
          Name                            kinesis_streams
          Match                           kinesis.2
          region                          us-east-1
          stream                          log-stream-dev
          role_arn                        <some_arn>
          auto_retry_requests             true
          workers                         3
          Retry_Limit                     5
      
      [OUTPUT]
          Name                            kinesis_streams
          Match                           kinesis.3
          region                          us-east-1
          stream                          log-stream-dev
          role_arn                        <some_arn>
          auto_retry_requests             true
          workers                         3
          Retry_Limit                     5

**Comment by Genry1** [comment] 2022-02-02 11:52
@matthewfala Just an update, I was able to catch broken connection errors with the latest aws-for-fluent-bit version (2.21.6).
`[2022/02/02 08:43:06] [error] [http_client] broken connection to kinesis.us-east-1.amazonaws.com:443 ?
[2022/02/02 08:43:06] [error] [http_client] broken connection to kinesis.us-east-1.amazonaws.com:443 ?
`
I tried with 826489191740.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-for-fluent-bit:1.8.11-1.8-event-loop-priority and the errors didn't show up, but no increase in the performance. Not yet clear for me where is the bottleneck.

**Comment by matthewfala** [comment] 2022-02-03 22:30
@Genry1, I talked to our team about this today. They think that this error may be due to kinesis api errors. I confirmed that in errors like the following:
```
[2022/01/31 12:18:14] [error] [output:kinesis_streams:kinesis_streams.0] 36 out of 500 records failed to be delivered, will retry this batch, log-stream-dev [2022/01/31 12:18:14] [error]
```
The error count, 36, is derived directly from kinesis's api response. It's normal for a few of these to come up, but if it happens more than five consecutive times on a certain batch, then your batch will be discarded due to your retry settings.

I'm wondering if that is why the team cannot reproduce your issue yet. Can you see if your kinesis stream has a high enough write/read capacity? The team thinks that increasing sharding on the stream may resolve the issues.

**Comment by Genry1** [comment] 2022-02-10 15:35
@matthewfala Seems that the bottleneck was not in the Output, but in the Input and Filters that I have. Seems that they are processed only by a single worker and it is not possible to parallelize the workload.

**Comment by Genry1** [comment] 2022-02-11 17:35
If you mean the problem about a single worker. I was testing a bit more today and the problems seems to be in the rotation mechanism. I tried increasing the Rotate_Wait to 60, but the problem is still there. 
I see that increasing the Buffer_Chunk_Size and Buffer_Max_Size to ~1MB helps a bit, but then the memory grows pretty quickly.
I tried to run 20.000 records/s over 300 seconds test, and expected to have 6.000.000 events as a result, but got 5.399.152. The CPU of Fluent Bit is not growing more than 95% out of 6 cores (600%) assigned, when I have only stdout output without Kinesis. 
I tried as well sending 40.000 records/s and the CPU wasn't going higher as well. When adding the Kinesis output the CPU stays around 140%.
Memory doesn't go more than 60 MB, it starts growing consistently to over 1 GB after I increase the Buffer_Chunk_Size and Buffer_Max_Size.

Why I am thinking that the problem is in the rotation, because I am having a counter on the messages and there are messages missing, in the end destination, from the head and tail of each file. 

I am running Fluent Bit on the t3.2xlarge instance running in TKS. The ebs volume is gp3 with size 20. The container is configured to have 3 files 500MB each. And fluent bit has 6 cores assigned.
Fluent Bit version is public.ecr.aws/aws-observability/aws-for-fluent-bit:2.21.6

This is the lines count from the files:
`
1607050 /var/lib/docker/containers/bae3b2ac19d51248a13095afc54538e81693c396dec235c2801405cb8fba1891/bae3b2ac19d51248a13095afc54538e81693c396dec235c2801405cb8fba1891-json.log
2194051 /var/lib/docker/containers/bae3b2ac19d51248a13095afc54538e81693c396dec235c2801405cb8fba1891/bae3b2ac19d51248a13095afc54538e81693c396dec235c2801405cb8fba1891-json.log.1
2198924 /var/lib/docker/containers/bae3b2ac19d51248a13095afc54538e81693c396dec235c2801405cb8fba1891/bae3b2ac19d51248a13095afc54538e81693c396dec235c2801405cb8fba1891-json.log.2
6000025 total
`

This is the result from Fluent Bit metrics:
`
{
"input": {
"tail.0": {
"records": 5399152,
"bytes": 1110515539,
"files_opened": 6,
"files_closed": 2,
"files_rotated": 2
}
},
"filter": {
"kubernetes.0": {
"drop_records": 0,
"add_records": 0
},
"nest.1": {
"drop_records": 0,
"add_records": 0
},
"modify.2": {
"drop_records": 0,
"add_records": 0
}
},
"output": {
"stdout.0": {
"proc_records": 5399152,
"proc_bytes": 4430994890,
"errors": 0,
"retries": 0,
"retries_failed": 0,
"dropped_records": 0,
"retried_records": 0
}
}
}
`

This is the Fluent Bit config:

      [SERVICE]
          Flush                           1
          Daemon                          Off
          Log_File                        /var/log/qtco-fluent-bit.log
          Log_Level                       info
          Parsers_File                    parsers.conf
          storage.path                    /var/log/qtco_flb_buffers
          storage.metrics                 On
          HTTP_Server                     On
          HTTP_Listen                     0.0.0.0
          HTTP_Port                       2021
      
      [INPUT]
          Name                            tail
          Path                            /var/log/containers/*.log
          Exclude_Path                    /var/log/containers/*fluent-bit*.log
          Tag                             kube.*
          Parser                          docker
          Skip_Long_Lines                 On
          Read_from_Head                  On
          Refresh_Interval                5
          Rotate_Wait                     60
          DB                              /var/log/flb.db
          Mem_Buf_Limit                   1.5GB
      
      # Parse log record
      [FILTER]
          Name                            kubernetes
          Match                           kube.var.log.*
          Merge_Log                       On
          Keep_Log                        Off
          K8S-Logging.Parser              On
          Buffer_Size                     50MB
          Labels                          Off
          Annotations                     On
          Kube_URL                        https://kubernetes.default.svc.cluster.local:443
          Use_Kubelet                     true
          Kubelet_Port                    10250
      
      [FILTER]
          Name                            nest
          Match                           kube.var.log.*
          Operation                       lift
          Nested_under                    kubernetes
      
      [FILTER]
          Name                            modify
          Match                           kube.var.log.*
          Rename                          namespace_name _role
          Rename                          host _private_ip
          Copy                            _private_ip _public_ip
          Add                             _realm dev-us1
          Add                             _availability_zone us-east-1
          Copy                            pod_id _host_sid
          Copy                            pod_id _instance_id
          Copy                            pod_name _private_hostname
          Copy                            pod_name _public_hostname
          Rename                          docker_id container_id
          Rename                          stream source
          Remove                          annotations
      
      [OUTPUT]
          Name                            stdout
          Match                           *

I hope this helps understanding the issue a bit better.

**Comment by matthewfala** [comment] 2022-02-11 19:57
Thank you @Genry1 for describing.

So it really sounds like a bug in the tail plugin at this point... as you described. Unless stdout & our aws plugins cause same problems which is unlikely.

I think that this is a really important bug to replicate, because log loss is something we greatly want to avoid, and a lot of the more demanding users use tail since it is able to handle throughput. Will consult team on working to resolve this issue.

Now, in terms of cpu underutilization due to lack of input parallelization, this is actually something the fluent bit team is stongly looking into, as well as parallelizing the filters which may come later. It would be great to share your findings with them. I'll let them know about the testing you did if I am included in the development of the parallelized feature.

However, I don't think that cpu underutilization should result in log loss if the code is error free, though it is possible that errors only appear if the cpu is maxed out. I think this is something worth looking into because others have experienced log loss with the tail plugin now that I think of it (though at the time we thought that it was the output plugins).

**Comment by matthewfala** [comment] 2022-02-11 20:52
Actually, how are you rotating your log files? Do you delete/archive the old log file immediately when rotating to a new file and update some kind of link? I don't have too much experience with the tail plugin's rotate (never tested that before).

If so, I agree that the solution is probably parallelization, since it may be that Fluent Bit is not able to read the whole log file before it is archived/replaced due to not being fast enough.

**Comment by Genry1** [comment] 2022-02-14 08:56
@matthewfala Thanks a lot for the feedback! It's very helpful. Will definitely share this info with Fluent Bit team. My goal was mainly to understand where to bottlenecks are and that we know the actual limits, and this helped a lot. 
Indeed the parallelization would help in here to take the load off the tail input, as now it seems to be a problem that it doesn't have enough resources when there are several filters being used, with kubernetes filter in particular.

As I understand the log file in "/var/log/containers/*.log" is linked via two links to "/var/lib/docker/containers/<container_id>/<container_id>-json.log". Once the file reaches the size limit, then it is renamed to the "...-json.log.1" and the new file is being created with the same name. There is not much information about it in the docs https://kubernetes.io/docs/concepts/cluster-administration/logging. But this is how it is supposed to work. 
If the files amount reaches the limit, then the old files will be deleted. The deletion doesn't seem to be a problem in our case, as all the files are still there.
This is the configuration that we are using for the log rotation in TKS:
`
"LogConfig":{"Type":"json-file","Config":{"max-buffer-size":"128m","max-file":"6","max-size":"500m","mode":"non-blocking"}}
`

**Comment by Genry1** [comment] 2022-02-14 13:46
Tried today to increate the Rotate_Wait to 120 seconds, and I was able to get tailed all the records correctly. So seems that the increasing to a higher values helps here. Even though it quite high already.

**Comment by matthewfala** [comment] 2022-04-25 20:49
Glad increasing Rotate_Wait helped.

Input parallelization seems to be on the upstream fluent bit roadmap and may be coming to fluent bit soon.
Closing this issue for now. Please reopen if you have any further concerns or questions. Thank you for your work, @Genry1, to help test aws-for-fluent-bit and get to the bottom of some performance issues.

**Closed by matthewfala** 2022-04-25 20:49 UTC
