### ISSUE TITLE
Exit Code 137 for the v2.12.0

### ISSUE THREAD

**Issue by ken5scal** [aws/aws-for-fluent-bit#174] opened 2021-04-23 02:02 UTC
We are triggering fargate tasks with aws cli. For the v2.12.0 fluentbit log router container fails because the container occasinally exits with exit code 137 when the main app container in the task finishes.

I have seen similar issue -> https://github.com/aws/aws-for-fluent-bit/issues/11

If you need more questions, please let me know

**Comment by PettitWesley** [comment] 2021-04-26 07:03
Is there anything interesting in fluent bit's logs from before it shuts down? Please share your fluent bit config as well. Also- what is the approximate throughput of logs that your application is outputting?

As noted in the issue you linked, that exit code means that docker had to SIGKILL fluent bit: https://github.com/aws/aws-for-fluent-bit/issues/11#issuecomment-565221578

While that shouldn't normally happen, it also isn't necessarily a bug...

> the container occasinally exits with exit code 137 when the main app container in the task finishes.

When the app container is killed fluent bit is sent a SIGTERM by ECS to tell it to clean up and shut down. It will gracefully handle this and try to clean everything up. If it can't complete clean up and send all pending logs in 30 seconds, it will get a SIGKILL to force it to stop. Taking more than 30 seconds to clean up is possible but not normal... we need more information to diagnose what is causing this.

**Comment by ken5scal** [comment] 2021-05-01 07:53
Thanks for your response.

The issue occurs in the ecs task which migrates the DB schema.
Whenever the schema is merged to our repository, the CI executes the `ecs run task` commands that only take about several minutes and outputs the log of migration result, which is about no more than 100 bytes or so.

As we read the #11, we increased the graceful time to be 30 seconds, just like following config.

```
[SERVICE]
    Grace          30
    Flush          1

[FILTER]
    Name           grep
    Match          *
    Exclude        log ^.*${IGNORE_PATH}.*$

[OUTPUT]
    Name           datadog
    Match          *
    Host           http-intake.logs.datadoghq.com
    TLS            on
    apikey         ${DD_API_KEY}
    dd_message_key log
    dd_source      ${DD_SOURCE}
    dd_service     ${DD_SERVICE}
    dd_tags        ${DD_TAGS}
    provider       ecs
    Retry_Limit    False
    TLS            on
```

Just in case, here is our ecs task definition.

```
{
  "executionRoleArn": "masked",
  "taskRoleArn": "masked",
  "containerDefinitions": [
    {
      "logConfiguration": {
        "logDriver": "awsfirelens",
        "secretOptions": [],
        "options": {}
      },
      "portMappings": [],
      "cpu": 512,
      "environment": [
        **masked**
      ],
      "mountPoints": [],
      "secrets": [
        **masked**
      ],
      "memoryReservation": 512,
      "volumesFrom": [],
      "image": "xxxxxx",
      "repositoryCredentials": {
        "credentialsParameter": "xxxxxxx"
      },
      "dependsOn": [
        {
          "containerName": "log_router",
          "condition": "START"
        }
      ],
      "essential": true,
      "name": "db-migration"
    },
    {
      "name": "log_router",
      "image": "xxxxxx",
      "essential": true,
      "repositoryCredentials": {
        "credentialsParameter": "xxxxxxx"
      },
      "firelensConfiguration": {
        "type": "fluentbit",
        "options": {
          "config-file-type": "file",
          "enable-ecs-log-metadata": "true",
          "config-file-value": "/fluent-bit/etc/ecs-fargate-dd-only.conf"
        }
      },
      "linuxParameters": {},
      "cpu": 0,
      "ulimits": [],
      "stopTimeout": 30,
      "environment": ["masked"],
      "secrets": ["masked"],
      "dockerSecurityOptions": [],
      "dockerLabels": {},
      "systemControls": []
    }
  ],
  "placementConstraints": [],
  "memory": "1024",
  "family": "db-migration",
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "512",
  "volumes": []
}```

**Comment by hossain-rayhan** [comment] 2021-05-03 17:13
Can you please share the detail fluent-bit logs (if we have any) and the version of fluent-bit you are using?

**Comment by ken5scal** [comment] 2021-05-17 02:03
@hossain-rayhan Thanks. Here is the logs

```
AWS for Fluent Bit Container Image Version 2.12.0
--
[1mFluent Bit v1.7.2[0m
* [1m[93mCopyright (C) 2019-2021 The Fluent Bit Authors[0m
* [1m[93mCopyright (C) 2015-2018 Treasure Data[0m
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2021/05/17 02:00:12] [ info] [engine] started (pid=1)
[2021/05/17 02:00:12] [ info] [storage] version=1.1.1, initializing...
[2021/05/17 02:00:12] [ info] [storage] in-memory
[2021/05/17 02:00:12] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/17 02:00:12] [ info] [input:tcp:tcp.0] listening on 127.0.0.1:8877
[2021/05/17 02:00:12] [ info] [input:forward:forward.1] listening on unix:///var/run/fluent.sock
[2021/05/17 02:00:12] [ info] [input:forward:forward.2] listening on 127.0.0.1:24224
[2021/05/17 02:00:13] [ info] [sp] stream processor started
[2021/05/17 02:00:15] [ info] [output:datadog:datadog.0] https://http-intake.logs.datadoghq.com, port=443, HTTP status=200 payload={}
```

...which exited with code 137.

![image](https://user-images.githubusercontent.com/9734362/118423246-8c32fe80-b6ff-11eb-9cbb-cbb0d6f0d5b7.png)

**Comment by PettitWesley** [comment] 2021-05-18 06:46
@ken5scal Are those all of the logs? We are specifically interested in the logs from right before it shuts down. Do the logs show that fluent bit received a signal like SIGTERM or SIGSEV or SIGKILL? (That would be in the logs).

As I noted in my comment, getting exit code 137 isn't necessarily bad or unexpected, it most likely just means that Fluent Bit was forcibly killed by ECS.

**Comment by ken5scal** [comment] 2021-05-21 07:56
@PettitWesley Yeah, it is the entire logs. I did not see any of signals.

**Comment by bklaubos** [comment] 2021-05-26 18:59
@PettitWesley 

Here's a sample :
```Fluent Bit v1.7.6
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2021/05/25 23:33:21] [ info] [engine] started (pid=1)
[2021/05/25 23:33:21] [ info] [storage] version=1.1.1, initializing...
[2021/05/25 23:33:21] [ info] [storage] in-memory
[2021/05/25 23:33:21] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/25 23:33:21] [ info] [output:s3:s3.0] Using upload size 100000000 bytes
[2021/05/25 23:33:21] [ info] [fstore] created root path /tmp/fluent-bit/xxxxxx
[2021/05/25 23:33:21] [ info] [sp] stream processor started
[2021/05/25 23:33:21] [ info] [input:tail:tail.0] inotify_fs_add(): inode=91257231 watch_fd=1 name=/app/logs/logs.txt
[2021/05/25 23:33:48] [engine] caught signal (SIGSEGV)
#0  0x7fab75956778      in  ???() at ???:0
```

**Comment by PettitWesley** [comment] 2021-05-26 20:16
Uh uh. SIGSEGV means segmentation fault... meaning the program caused itself to crash, likely indicating a bug in the code...

**Comment by zhonghui12** [comment] 2021-09-01 17:54
Hi @ken5scal, do you still have this issue? We've had many releases after v2.12.0 so could you please upgrade to the latest version to see if the problem still exists? Thanks

**Comment by f0o** [comment] 2021-09-08 09:35
@zhonghui12 did v2.12.0 update the `latest` tag? If so then I can confirm that it's still an issue

**Comment by PettitWesley** [comment] 2021-09-14 04:23
@f0o Yeah that image sha is our latest. Are you willing to deploy a debug version of the image? How repeatable is this? Without a stack trace, there is not much we can do. If I send you a debug version built with [Valgrind](https://valgrind.org/), it'll be a lot slower than normal fluent bit and use a bit more memory... but if it crashes then the logs should give us clear indication of what caused the problem, and then we might be able to fix it. 

If you want a quicker resolution, my other suggestion is to try out other recent image tags, or our stable tag: https://github.com/aws/aws-for-fluent-bit#using-the-stable-tag

**Comment by f0o** [comment] 2021-09-20 14:03
Absolutely what tag would the debug be? (Sorry for the delay, vacay came in)

About the repeatability, we run quite many of these services so we probably get 10-20 of those issues per day

**Comment by PettitWesley** [comment] 2021-09-20 16:00
@f0o There is no tag for debug... though actually automatically building a valgrind debug image is an interesting idea that I might take... right now I have to build it custom for you... will do that later today.

**Comment by f0o** [comment] 2021-09-20 16:03
@PettitWesley haha thanks, I appreciate! Let me know and I'll toss it into our env and observe the alarms :)

**Comment by f0o** [comment] 2021-09-21 14:10
@PettitWesley we just got exitcode 137 using the `stable` tag... Cant see any crash in the cloudwatch logs for Firelens container unfortunately

```
2021-09-21 14:02:29
AWS for Fluent Bit Container Image Version 2.16.1
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ info] [engine] service stopped
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ info] [task] tcp/tcp.0 has 0 pending task(s):
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ info] [task] forward/forward.1 has 1 pending task(s):
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ info] [task] task_id=0 still running on route(s): forward/forward.2
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ info] [task] forward/forward.2 has 0 pending task(s):
2021-09-21 14:02:29
[2021/09/21 14:02:29] [ warn] [engine] service will stop in 5 seconds
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ info] [engine] service stopped
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ info] [task] tcp/tcp.0 has 0 pending task(s):
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ info] [task] forward/forward.1 has 1 pending task(s):
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ info] [task] task_id=0 still running on route(s): forward/forward.2
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ info] [task] forward/forward.2 has 0 pending task(s):
2021-09-21 14:02:24
[2021/09/21 14:02:24] [ warn] [engine] service will stop in 5 seconds
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ info] [engine] service stopped
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ info] [task] tcp/tcp.0 has 0 pending task(s):
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ info] [task] forward/forward.1 has 1 pending task(s):
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ info] [task] task_id=0 still running on route(s): forward/forward.2
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ info] [task] forward/forward.2 has 0 pending task(s):
2021-09-21 14:02:19
[2021/09/21 14:02:19] [ warn] [engine] service will stop in 5 seconds
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ info] [engine] service stopped
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ info] [task] tcp/tcp.0 has 0 pending task(s):
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ info] [task] forward/forward.1 has 1 pending task(s):
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ info] [task] task_id=0 still running on route(s): forward/forward.2
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ info] [task] forward/forward.2 has 0 pending task(s):
2021-09-21 14:02:14
[2021/09/21 14:02:14] [ warn] [engine] service will stop in 5 seconds
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ info] [engine] service stopped
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ info] [task] tcp/tcp.0 has 0 pending task(s):
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ info] [task] forward/forward.1 has 1 pending task(s):
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ info] [task] task_id=0 still running on route(s): forward/forward.2
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ info] [task] forward/forward.2 has 0 pending task(s):
2021-09-21 14:02:09
[2021/09/21 14:02:09] [ warn] [engine] service will stop in 5 seconds
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ info] [engine] service stopped
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ info] [task] tcp/tcp.0 has 0 pending task(s):
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ info] [task] forward/forward.1 has 1 pending task(s):
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ info] [task] task_id=0 still running on route(s): forward/forward.2
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ info] [task] forward/forward.2 has 0 pending task(s):
2021-09-21 14:02:04
[2021/09/21 14:02:04] [ warn] [engine] service will stop in 5 seconds
2021-09-21 14:01:59
[2021/09/21 14:01:59] [engine] caught signal (SIGTERM)
```

**Comment by f0o** [comment] 2021-09-22 08:49
Maybe related to https://github.com/fluent/fluent-bit/pull/2885#issuecomment-762243123 ?

Could it be that the container runtime posts SIGKILL after waiting for 30s for the container to have stopped through SIGTERM?

**Comment by f0o** [comment] 2021-09-22 09:12
After looking more and more into the code of fluent-bit I believe that signals are not handled right.

I've added `tini` to the Dockerfile from this repo and am testing the resulting image from `make release` now... Wish me luck!

**Comment by PettitWesley** [comment] 2021-09-22 15:58
@f0o Apologies... I got distracted and forgot to build an image and look into this more... I promise I will get to it today in the next 12 hours.

**Comment by PettitWesley** [comment] 2021-09-22 22:47
@f0o 

> Could it be that the container runtime posts SIGKILL after waiting for 30s for the container to have stopped through SIGTERM?

Yes I believe you are correct. In ECS and EKS we give a SIGTERM then 30s later, a SIGKILL. If the SIGKILL was needed, then your exit code is expected to be 137 IIRC.

**Comment by PettitWesley** [comment] 2021-09-22 22:53
Also, for the valgrind debug image... so basically all I do is just install valgrind in our [Dockerfile](https://github.com/aws/aws-for-fluent-bit/blob/mainline/Dockerfile) and then customize the [entrypoint](https://github.com/aws/aws-for-fluent-bit/blob/mainline/entrypoint.sh). If you're building your own image already, you can do that yourself. 

I can also do it too if its more convenient, but I suspect this SIGSEGV might be the same as other reports we are getting from other customers... we are working on a number of fixes which will take time to get into upstream. Right now, we are testing out this branch: https://github.com/krispraws/fluent-bit/commits/v1_7_5_openssl_fix

If you want a custom build from a fork, its very easy, Just customize the Dockerfile like I did here: https://github.com/PettitWesley/aws-for-fluent-bit/commit/cad233de37eec2174f00c5f1e2fcd04143f81415

**Comment by f0o** [comment] 2021-09-23 10:49
> @f0o
> 
> > Could it be that the container runtime posts SIGKILL after waiting for 30s for the container to have stopped through SIGTERM?
> 
> Yes I believe you are correct. In ECS and EKS we give a SIGTERM then 30s later, a SIGKILL. If the SIGKILL was needed, then your exit code is expected to be 137 IIRC.

Ok then we're getting closer! So what can be is that the fluentbit PR I linked is the actual way to solve this then. Because from the PR I see that it would just wait forever for any tasks to be finished in the shutdown sequence, which deffo exceeds 30s!

However it's worth to note that the addition of `tini` has done something to the stability, we have only registered one alert in the entire day yesterday whereas without we would register at least one per hour.

I'll dig deeper... I'm a but confused as to what forward/forward.1 refers to as there's an input called forward.1 (the Unix socket) but my output is also technically a forward...

But the root cause seems to be pending tasks in the shutdown sequence.

**Comment by PettitWesley** [comment] 2021-10-04 05:50
@f0o Sorry I forgot to look back at this issue for a while.

> Because from the PR I see that it would just wait forever for any tasks to be finished in the shutdown sequence, which deffo exceeds 30s!

This is interesting... we have a different report that when it receives a SIGTERM it then stops accepting logs on the forward input and thus logs are lost. 

I've added looking into SIGTERM/graceful shutdown behavior on my Fluent Bit roadmap wishlist. I can't promise any timeline, but we'll look into it eventually. I think we probably do need to make it user configurable.

> I'll dig deeper... I'm a but confused as to what forward/forward.1 refers to as there's an input called forward.1 (the Unix socket) but my output is also technically a forward...

I looked at the code for this, its in `flb_task.c` in `flb_task_running_print()`. It seems routes = outputs, and the pending message is for inputs.

**Comment by f0o** [comment] 2021-10-04 06:26
@PettitWesley
> I looked at the code for this, its in flb_task.c in flb_task_running_print(). It seems routes = outputs, and the pending message is for inputs.

Yeah that covers what I could deduct so far... Whenever the fluentbit loses connection to the NLB for whatever reason it will keep a pending task which prevents it from shutting down properly thus exiting with 137.

I've spent last week trying to debug the NLB's "failure" thinking it might be an easier solution than fiddling with fluentbit but to my understanding everything is fine with the NLB assuming there arent any TCP connection limits hit (Which I couldn't find any limits for)

I'm going to merge the PR into this repo and build an image out of it to test it against and will post back with any results

**Comment by PettitWesley** [comment] 2021-11-21 18:28
This upstream PR ensures that Fluent Bit will actually gracefully shut down once the grace period ends: https://github.com/fluent/fluent-bit/pull/4355

This might be one reason why you were seeing this exit code- Fluent Bit was being force killed by the SIGKILL, instead of gracefully shutting down and terminating itself at the end of the grace period.

**Comment by f0o** [comment] 2021-12-15 09:24
Now that the PR is merged it should be pulled in by the next release of AWS-For-Fluent-Bit right?

Any idea when that might be?

I tried the current `latest` tag but just got hit with the same issue again yesterday. Will revert back to my own little patched version

**Comment by f0o** [comment] 2022-01-04 07:41
@PettitWesley Now that 2.21.5 released, I am a bit wondering about where to configure the graceful-shutdown timeout (30s for fargate)... It seems that it should be included in the base-config of aws-for-fluent-bit, namely https://github.com/aws/aws-for-fluent-bit/blob/mainline/fluent-bit.conf - or am I mistaken?

If that's the case, shouldn't the 2.21.5 release have included that?

**Comment by PettitWesley** [comment] 2022-01-07 22:30
@f0o You have to customize the Fluent Bit configuration. 

In FireLens on Fargate, this would be the option: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/config-file-type-file

And then you'd have:

```
[SERVICE]
     Grace 30
```

> https://github.com/aws/aws-for-fluent-bit/blob/mainline/fluent-bit.conf - 

This is the default config file which almost no one uses. You add your own by creating a new image, or by mounting in the config somehow.

**Comment by f0o** [comment] 2022-01-10 09:58
@PettitWesley Really dont want to maintain a custom image for just 1 changed setting 😅 

But on the Up-Side, The default uses 5 Secs and it does actually shutdown in a timely manner so for us 2.21.5 did actually solve the issue!

So 👍  from our POV

**Comment by PettitWesley** [comment] 2022-01-10 18:41
@f0o One option is as shown in this blog: https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

```
"firelensConfiguration": {
    "type": "fluentbit",
    "options": {
        "config-file-type": "file",
        "config-file-value": "/fluent-bit/configs/minimize-log-loss.conf"
    }
}
```

This config sets the grace to 30: https://github.com/aws/aws-for-fluent-bit/blob/mainline/configs/minimize-log-loss.conf

**Comment by jsluke** [comment] 2022-05-09 21:58
Hi, I just want to add my 2c to this issue. I think I have been running into the same issue as the original author of the ticket. The symptoms are that the fluent-bit container exits with 137 intermittently, and when it fails this way its logs do not show that it ever caught SIGTERM. The task sometimes hardly has any work to do so it can exit very quickly. The only thing that has seemed to fix this is to configure a health check for the fluent-bit container and set a "HEALTHY" container dependency inside the essential container definitions. FYI setting the dependency to "START" did not fix the issue. I used the health check found here and it did the trick -> https://github.com/aws-samples/amazon-ecs-firelens-under-the-hood/blob/mainline/generated-configs/fluent-bit/README.md

My guess is that the essential container exits before the fluent-bit container has registered for SIGTERM. It just sits around until ECS forcibly kills it. I was able to reproduce using the Docker hello-world container. The task looks something like this:

```
{
    "containerDefinitions": [
      {
        "name": "log_router",
        "image": "amazon/aws-for-fluent-bit:stable",
        "logConfiguration": {
          "logDriver": "awslogs",
          "options": {
            "awslogs-group": "[redacted]",
            "awslogs-region": "us-west-2"
          }
        },
        "firelensConfiguration": {
          "type": "fluentbit",
          "options": {
            "config-file-type": "file",
            "enable-ecs-log-metadata": "true",
            "config-file-value": "/fluent-bit/configs/minimize-log-loss.conf"
          }
        }
      },
      {
        "image": "hello-world:latest",
        "name": "hello-world",
        "logConfiguration": {
          "logDriver": "awsfirelens",
          "options": {
            "dd_message_key": "log",
            "apikey": "[redacted]",
            "provider": "ecs",
            "dd_service": "fluent-bit-test",
            "Host": "http-intake.logs.datadoghq.com",
            "TLS": "on",
            "dd_source": "[redacted]",
            "dd_tags": "[redacted]",
            "Name": "datadog"
          }
        }
      }
    ],
    "compatibilities": [
      "EC2",
      "FARGATE"
    ],
    "requiresCompatibilities": [
      "FARGATE"
    ],
    "networkMode": "awsvpc",
    "runtimePlatform": {
      "operatingSystemFamily": "LINUX",
    },
    "memory": "512",
    "cpu": "256"
  }
```

**Comment by PettitWesley** [comment] 2022-05-24 01:23
@jsluke For health check guidance, please see: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/health-check

**Comment by sparrc** [comment] 2024-10-14 18:30
The original Q in this ticket appears to have been answered. Closing for inactivity, please feel free to open a new ticket if more information is needed.

**Closed by sparrc** 2024-10-14 18:30 UTC
Labels: pending response
